server:
  port: 8080
  mode: "debug"  # debug or release
  auth_enabled: true  # enable/disable authentication

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "your-password"
  dbname: "lauth"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""  # Redis password, leave empty if not set
  db: 0        # Redis database number

jwt:
  secret: "your-jwt-secret"
  access_token_expire: 24  # 访问令牌过期时间(小时)
  refresh_token_expire: 168 # 刷新令牌过期时间(小时)

oidc:
  issuer: "http://localhost:8080"
  private_key_path: "config/keys/oidc.key"
  public_key_path: "config/keys/oidc.pub" 