server:
  port: 8080
  mode: "debug"  # debug or release
  auth_enabled: true  # enable/disable authentication

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "your-password"
  dbname: "lauth"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""  # Redis password, leave empty if not set
  db: 0        # Redis database number

jwt:
  secret: "your-jwt-secret"
  access_token_expire: 24  # Access token expiration time (hours)
  refresh_token_expire: 168 # Refresh token expiration time (hours)

oidc:
  issuer: "http://localhost:8080"
  private_key_path: "config/keys/oidc.key"
  public_key_path: "config/keys/oidc.pub"

audit:
  log_dir: "logs/audit"  # Audit log storage directory
  rotation_size: 10485760  # Log file rotation size, in bytes, default 10MB
  retention_days: 90  # Log retention days
  websocket:
    ping_interval: 30  # WebSocket heartbeat interval, in seconds
    write_wait: 10    # WebSocket write timeout, in seconds
    read_wait: 60     # WebSocket read timeout, in seconds
    max_message_size: 1024  # WebSocket maximum message size, in bytes 

smtp:
  # Basic configuration
  host: "smtp.example.com"  # SMTP server address
  port: 465  # SMTP server port (QQ email uses port 465)
  username: "your-email@example.com"  # Your email account
  password: "your-smtp-password"  # Your SMTP password (QQ email requires authorization code)
  from_name: "Lauth System"  # Sender display name
  from_email: "your-email@example.com"  # Sender email
  template_path: "templates/email"  # Email template path

  # Security configuration
  insecure_skip_verify: false  # Whether to skip TLS certificate verification, recommended to set to false in production
  
  # Timeout configuration
  connect_timeout: 30  # Connection timeout (seconds)
  send_timeout: 30  # Send timeout (seconds) 
